# Generated by Django 4.2.1 on 2023-06-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesnsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='read_text',
            field=models.TextField(blank=True, default='test_admin', null=True),
        ),
    ]
