# Generated by Django 4.2.1 on 2023-06-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesnsapp', '0002_alter_postmodel_good_alter_postmodel_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='good',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='read',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
